name: 'Build packages'
on:
  pull_request:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build faasd 🔧
        run: |
          nix build -L .#faasd --accept-flake-config
      - name: Build containerd 🔧
        run: |
          nix build -L .#faasd-containerd --accept-flake-config
      - name: Build cni-plugin 🔧
        run: |
          nix build -L .#faasd-cni-plugins --accept-flake-config
      - name: Build OpenFaaS core images 🔧
        run: |
          nix build --accept-flake-config \
            .#gateway-image \
            .#queue-worker-image \
            .#nats-image \
            .#prometheus-image
      - name: Check flake
        run: nix flake check -L --accept-flake-config
